
// "use client"
// import React, { useEffect, useState } from 'react'
import { MineCard } from './_components/MineCard';
import MiniCard from './_components/MiniCard';
import MiniCard2 from './_components/MiniCard2';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import axios from "axios";
// const mines = [
//     {
//         "Mine_ID": 1,
//         "Mine_Name": "Raniganj Mine",
//         "Mine_Type": "Open-cast",
//         "State": "West Bengal",
//         "Latitude": 23.622,
//         "Longitude": 87.085,
//         "Coal_Production": 1000000,
//         "Area_Covered": 1200,
//         "Year_Started": 1965,
//         "Fuel_Consumption": 25000000,
//         "Electricity_Consumption": 50,
//         "Explosives_Used": 12000,
//         "Methane_Emissions": 100,
//         "Fugitive_Emissions": 50,
//         "CO2_Emissions": 250000,
//         "CH4_CO2e": 1250,
//         "Afforestation_Potential": 100,
//         "Trees_Plantable": 100000,
//         "Carbon_Sequestration_Potential": 1000,
//         "Deforestation_Impact": 2000,
//         "Methane_Capture_Potential": 75,
//         "Energy_Efficiency_Gains": 2.5,
//         "Electrification_Impact": 57.5,
//         "Renewable_Adoption_Potential": 15,
//         "Carbon_Credits_Potential": 1145,
//         "Carbon_Credit_Value": 30,
//         "Estimated_Revenue_from_Credits ": 34350,
//         "Air_Quantity (m3/minute)": 1875.24,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.1647,
//         "Make_of_Methane (m3/minute)": 3.08852028,
//         "CO2_conc._in_intake (%)": 0.0346,
//         "CO2_conc._in_return (%)": 0.1866,
//         "Make_of_CO2 (m3/minute)": 2.8503648,
//         "Coal_Production (TPD)": 485,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 9.170039594,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 8.462938788,
//         "Description": "The Raniganj Mine is one of the oldest coal mines in India, operating since 1965. It is an open-cast mine located in West Bengal, known for its significant contribution to coal production. The mine also explores opportunities for afforestation and methane capture to minimize environmental impacts."
//     },
//     {
//         "Mine_ID": 2,
//         "Mine_Name": "Singareni Mine",
//         "Mine_Type": "Underground",
//         "State": "Telangana",
//         "Latitude": 18.383,
//         "Longitude": 79.813,
//         "Coal_Production": 500000,
//         "Area_Covered": 800,
//         "Year_Started": 1972,
//         "Fuel_Consumption": 12000000,
//         "Electricity_Consumption": 30,
//         "Explosives_Used": 7000,
//         "Methane_Emissions": 80,
//         "Fugitive_Emissions": 40,
//         "CO2_Emissions": 125000,
//         "CH4_CO2e": 1000,
//         "Afforestation_Potential": 50,
//         "Trees_Plantable": 50000,
//         "Carbon_Sequestration_Potential": 500,
//         "Deforestation_Impact": 1000,
//         "Methane_Capture_Potential": 60,
//         "Energy_Efficiency_Gains": 1.5,
//         "Electrification_Impact": 27.6,
//         "Renewable_Adoption_Potential": 9,
//         "Carbon_Credits_Potential": 648,
//         "Carbon_Credit_Value": 28,
//         "Estimated_Revenue_from_Credits ": 18144,
//         "Air_Quantity (m3/minute)": 1315.02,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.1982,
//         "Make_of_Methane (m3/minute)": 2.60636964,
//         "CO2_conc._in_intake (%)": 0.0342,
//         "CO2_conc._in_return (%)": 0.1228,
//         "Make_of_CO2 (m3/minute)": 1.16510772,
//         "Coal_Production (TPD)": 20,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 187.6586141,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 83.88775584,
//         "Description": "Singareni Mine, an underground coal mine located in Telangana, has been operational since 1972. It employs advanced underground mining techniques and actively works on reducing methane and CO2 emissions through energy efficiency and methane capture initiatives."
//     },
//     {
//         "Mine_ID": 3,
//         "Mine_Name": "Korba Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Chhattisgarh",
//         "Latitude": 22.357,
//         "Longitude": 82.683,
//         "Coal_Production": 1500000,
//         "Area_Covered": 2000,
//         "Year_Started": 1980,
//         "Fuel_Consumption": 30000000,
//         "Electricity_Consumption": 75,
//         "Explosives_Used": 18000,
//         "Methane_Emissions": 150,
//         "Fugitive_Emissions": 75,
//         "CO2_Emissions": 375000,
//         "CH4_CO2e": 1875,
//         "Afforestation_Potential": 150,
//         "Trees_Plantable": 150000,
//         "Carbon_Sequestration_Potential": 1500,
//         "Deforestation_Impact": 3000,
//         "Methane_Capture_Potential": 112.5,
//         "Energy_Efficiency_Gains": 3.75,
//         "Electrification_Impact": 69,
//         "Renewable_Adoption_Potential": 22.5,
//         "Carbon_Credits_Potential": 1800,
//         "Carbon_Credit_Value": 32,
//         "Estimated_Revenue_from_Credits ": 57600,
//         "Air_Quantity (m3/minute)": 2186.89,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.6018,
//         "Make_of_Methane (m3/minute)": 13.16070402,
//         "CO2_conc._in_intake (%)": 0.0339,
//         "CO2_conc._in_return (%)": 0.1863,
//         "Make_of_CO2 (m3/minute)": 3.33282036,
//         "Coal_Production (TPD)": 100,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 189.5141379,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 47.99261318,
//         "Description": "Korba Mine is an open-cast coal mine in Chhattisgarh, started in 1980. It covers a large area and produces substantial amounts of coal. The mine is focused on increasing energy efficiency, capturing methane emissions, and implementing afforestation to offset environmental impact."
//     },
//     {
//         "Mine_ID": 4,
//         "Mine_Name": "Talcher Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Odisha",
//         "Latitude": 20.95,
//         "Longitude": 85.25,
//         "Coal_Production": 2000000,
//         "Area_Covered": 2500,
//         "Year_Started": 1975,
//         "Fuel_Consumption": 45000000,
//         "Electricity_Consumption": 100,
//         "Explosives_Used": 20000,
//         "Methane_Emissions": 200,
//         "Fugitive_Emissions": 100,
//         "CO2_Emissions": 500000,
//         "CH4_CO2e": 2500,
//         "Afforestation_Potential": 200,
//         "Trees_Plantable": 200000,
//         "Carbon_Sequestration_Potential": 2000,
//         "Deforestation_Impact": 4000,
//         "Methane_Capture_Potential": 150,
//         "Energy_Efficiency_Gains": 5,
//         "Electrification_Impact": 100,
//         "Renewable_Adoption_Potential": 30,
//         "Carbon_Credits_Potential": 2750,
//         "Carbon_Credit_Value": 35,
//         "Estimated_Revenue_from_Credits ": 96250,
//         "Air_Quantity (m3/minute)": 2500.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.7429,
//         "Make_of_Methane (m3/minute)": 18.57351458,
//         "CO2_conc._in_intake (%)": 0.0344,
//         "CO2_conc._in_return (%)": 0.2266,
//         "Make_of_CO2 (m3/minute)": 5.91913112,
//         "Coal_Production (TPD)": 250,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 108.8117479,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 21.45288451,
//         "Description": "Talcher Mine, located in Odisha, is an open-cast mine that began operations in 1975. It is one of the largest coal-producing mines in the region, with a strong focus on renewable energy adoption and carbon credit potential to reduce its carbon footprint."
//     },
//     {
//         "Mine_ID": 5,
//         "Mine_Name": "Jharia Mine",
//         "Mine_Type": "Underground",
//         "State": "Jharkhand",
//         "Latitude": 23.75,
//         "Longitude": 86.42,
//         "Coal_Production": 800000,
//         "Area_Covered": 1500,
//         "Year_Started": 1960,
//         "Fuel_Consumption": 20000000,
//         "Electricity_Consumption": 40,
//         "Explosives_Used": 10000,
//         "Methane_Emissions": 120,
//         "Fugitive_Emissions": 60,
//         "CO2_Emissions": 200000,
//         "CH4_CO2e": 1500,
//         "Afforestation_Potential": 80,
//         "Trees_Plantable": 80000,
//         "Carbon_Sequestration_Potential": 800,
//         "Deforestation_Impact": 1600,
//         "Methane_Capture_Potential": 90,
//         "Energy_Efficiency_Gains": 2,
//         "Electrification_Impact": 50,
//         "Renewable_Adoption_Potential": 20,
//         "Carbon_Credits_Potential": 1620,
//         "Carbon_Credit_Value": 30,
//         "Estimated_Revenue_from_Credits ": 48600,
//         "Air_Quantity (m3/minute)": 1750.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.5236,
//         "Make_of_Methane (m3/minute)": 9.163,
//         "CO2_conc._in_intake (%)": 0.0341,
//         "CO2_conc._in_return (%)": 0.1735,
//         "Make_of_CO2 (m3/minute)": 2.325,
//         "Coal_Production (TPD)": 125,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 73.3,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 18.6,
//         "Description": "Jharia Mine is a historic underground coal mine in Jharkhand, operational since 1960. It is known for its methane capture efforts and afforestation potential, balancing coal production with environmental sustainability."
//     },
//     {
//         "Mine_ID": 6,
//         "Mine_Name": "Bokaro Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Jharkhand",
//         "Latitude": 23.67,
//         "Longitude": 86.14,
//         "Coal_Production": 1800000,
//         "Area_Covered": 2300,
//         "Year_Started": 1970,
//         "Fuel_Consumption": 35000000,
//         "Electricity_Consumption": 90,
//         "Explosives_Used": 16000,
//         "Methane_Emissions": 180,
//         "Fugitive_Emissions": 90,
//         "CO2_Emissions": 450000,
//         "CH4_CO2e": 2250,
//         "Afforestation_Potential": 160,
//         "Trees_Plantable": 160000,
//         "Carbon_Sequestration_Potential": 1600,
//         "Deforestation_Impact": 3200,
//         "Methane_Capture_Potential": 135,
//         "Energy_Efficiency_Gains": 4,
//         "Electrification_Impact": 70,
//         "Renewable_Adoption_Potential": 25,
//         "Carbon_Credits_Potential": 2350,
//         "Carbon_Credit_Value": 33,
//         "Estimated_Revenue_from_Credits ": 77550,
//         "Air_Quantity (m3/minute)": 2100.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.6824,
//         "Make_of_Methane (m3/minute)": 13.225,
//         "CO2_conc._in_intake (%)": 0.0345,
//         "CO2_conc._in_return (%)": 0.1885,
//         "Make_of_CO2 (m3/minute)": 3.114,
//         "Coal_Production (TPD)": 300,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 44.1,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 10.4,
//         "Description": "Bokaro Mine is known for its significant open-cast operations and extensive coal production. It has high afforestation and carbon sequestration potential, with a robust carbon credit revenue opportunity."
//     },
//     {
//         "Mine_ID": 7,
//         "Mine_Name": "WCL Chandrapur Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Maharashtra",
//         "Latitude": 20.01,
//         "Longitude": 79.3,
//         "Coal_Production": 2500000,
//         "Area_Covered": 3000,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 50000000,
//         "Electricity_Consumption": 120,
//         "Explosives_Used": 22000,
//         "Methane_Emissions": 300,
//         "Fugitive_Emissions": 150,
//         "CO2_Emissions": 625000,
//         "CH4_CO2e": 3750,
//         "Afforestation_Potential": 200,
//         "Trees_Plantable": 300000,
//         "Carbon_Sequestration_Potential": 2000,
//         "Deforestation_Impact": 5000,
//         "Methane_Capture_Potential": 200,
//         "Energy_Efficiency_Gains": 5,
//         "Electrification_Impact": 120,
//         "Renewable_Adoption_Potential": 35,
//         "Carbon_Credits_Potential": 4000,
//         "Carbon_Credit_Value": 37,
//         "Estimated_Revenue_from_Credits ": 148000,
//         "Air_Quantity (m3/minute)": 2500.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.8461,
//         "Make_of_Methane (m3/minute)": 20.113,
//         "CO2_conc._in_intake (%)": 0.0348,
//         "CO2_conc._in_return (%)": 0.2012,
//         "Make_of_CO2 (m3/minute)": 5.013,
//         "Coal_Production (TPD)": 350,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 57.5,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 14.3,
//         "Description": "WCL Chandrapur Mine is an open-cast coal mine located in Maharashtra, India. Established in 1985, it covers an area of 3,000 hectares and produces approximately 2.5 million tons of coal annually. The mine consumes 50 million liters of fuel and 120 MWh of electricity per year. Explosives usage amounts to 22,000 kg annually, contributing to methane emissions of 300 tons and CO₂ emissions of 625,000 tons."
//     },
//     {
//         "Mine_ID": 8,
//         "Mine_Name": "Neyveli Lignite Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Tamil Nadu",
//         "Latitude": 11.61,
//         "Longitude": 79.49,
//         "Coal_Production": 3000000,
//         "Area_Covered": 3500,
//         "Year_Started": 1990,
//         "Fuel_Consumption": 60000000,
//         "Electricity_Consumption": 150,
//         "Explosives_Used": 25000,
//         "Methane_Emissions": 350,
//         "Fugitive_Emissions": 175,
//         "CO2_Emissions": 750000,
//         "CH4_CO2e": 4375,
//         "Afforestation_Potential": 250,
//         "Trees_Plantable": 400000,
//         "Carbon_Sequestration_Potential": 2500,
//         "Deforestation_Impact": 6000,
//         "Methane_Capture_Potential": 250,
//         "Energy_Efficiency_Gains": 7,
//         "Electrification_Impact": 150,
//         "Renewable_Adoption_Potential": 40,
//         "Carbon_Credits_Potential": 5000,
//         "Carbon_Credit_Value": 40,
//         "Estimated_Revenue_from_Credits ": 200000,
//         "Air_Quantity (m3/minute)": 2750.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.9234,
//         "Make_of_Methane (m3/minute)": 22.234,
//         "CO2_conc._in_intake (%)": 0.0351,
//         "CO2_conc._in_return (%)": 0.2147,
//         "Make_of_CO2 (m3/minute)": 6.033,
//         "Coal_Production (TPD)": 400,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 55.6,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 13.2,
//         "Description": "Neyveli Mine is a prominent open-cast mine with a very high coal production rate. It has a large afforestation and carbon sequestration potential, along with significant renewable energy adoption and carbon credit opportunities."
//     },
//     {
//         "Mine_ID": 9,
//         "Mine_Name": "Korba Mine",
//         "Mine_Type": "Underground",
//         "State": "Chhattisgarh",
//         "Latitude": 22.35,
//         "Longitude": 82.68,
//         "Coal_Production": 900000,
//         "Area_Covered": 2000,
//         "Year_Started": 1975,
//         "Fuel_Consumption": 25000000,
//         "Electricity_Consumption": 60,
//         "Explosives_Used": 12000,
//         "Methane_Emissions": 130,
//         "Fugitive_Emissions": 65,
//         "CO2_Emissions": 225000,
//         "CH4_CO2e": 1625,
//         "Afforestation_Potential": 100,
//         "Trees_Plantable": 100000,
//         "Carbon_Sequestration_Potential": 1000,
//         "Deforestation_Impact": 2000,
//         "Methane_Capture_Potential": 100,
//         "Energy_Efficiency_Gains": 3,
//         "Electrification_Impact": 60,
//         "Renewable_Adoption_Potential": 25,
//         "Carbon_Credits_Potential": 1725,
//         "Carbon_Credit_Value": 32,
//         "Estimated_Revenue_from_Credits ": 55200,
//         "Air_Quantity (m3/minute)": 1900.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.5442,
//         "Make_of_Methane (m3/minute)": 10.245,
//         "CO2_conc._in_intake (%)": 0.0342,
//         "CO2_conc._in_return (%)": 0.1745,
//         "Make_of_CO2 (m3/minute)": 2.615,
//         "Coal_Production (TPD)": 135,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 76.3,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 19.2,
//         "Description": "Korba Mine is an underground coal mine in Chhattisgarh, India, operating since 1975. With an annual coal production of 900,000 tons, it covers an area of 2,000 hectares. The mine consumes 25 million liters of fuel and 60 MWh of electricity per year. It emits 130 tons of methane and 225,000 tons of CO₂ annually. The mine has the potential to plant 100,000 trees on 100 hectares, sequestering 1,000 tons of carbon."
//     },
//     {
//         "Mine_ID": 10,
//         "Mine_Name": "Talcher Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Odisha",
//         "Latitude": 20.95,
//         "Longitude": 85.23,
//         "Coal_Production": 3500000,
//         "Area_Covered": 4000,
//         "Year_Started": 1995,
//         "Fuel_Consumption": 70000000,
//         "Electricity_Consumption": 200,
//         "Explosives_Used": 35000,
//         "Methane_Emissions": 400,
//         "Fugitive_Emissions": 200,
//         "CO2_Emissions": 875000,
//         "CH4_CO2e": 5000,
//         "Afforestation_Potential": 300,
//         "Trees_Plantable": 450000,
//         "Carbon_Sequestration_Potential": 3000,
//         "Deforestation_Impact": 7500,
//         "Methane_Capture_Potential": 300,
//         "Energy_Efficiency_Gains": 8,
//         "Electrification_Impact": 200,
//         "Renewable_Adoption_Potential": 50,
//         "Carbon_Credits_Potential": 5300,
//         "Carbon_Credit_Value": 38,
//         "Estimated_Revenue_from_Credits ": 201400,
//         "Air_Quantity (m3/minute)": 3000.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.9723,
//         "Make_of_Methane (m3/minute)": 25.114,
//         "CO2_conc._in_intake (%)": 0.0354,
//         "CO2_conc._in_return (%)": 0.2254,
//         "Make_of_CO2 (m3/minute)": 6.414,
//         "Coal_Production (TPD)": 450,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 55.8,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 14.7,
//         "Description": "Talcher Mine is an open-cast coal mine located in Odisha, India, established in 1995. It spans 4,000 hectares and produces 3.5 million tons of coal annually. The mine consumes 70 million liters of fuel and 200 MWh of electricity each year. Methane emissions reach 400 tons, with CO₂ emissions totaling 875,000 tons"
//     },
//     {
//         "Mine_ID": 11,
//         "Mine_Name": "Raniganj Mine",
//         "Mine_Type": "Underground",
//         "State": "West Bengal",
//         "Latitude": 23.62,
//         "Longitude": 87.08,
//         "Coal_Production": 750000,
//         "Area_Covered": 1500,
//         "Year_Started": 1965,
//         "Fuel_Consumption": 20000000,
//         "Electricity_Consumption": 50,
//         "Explosives_Used": 10000,
//         "Methane_Emissions": 100,
//         "Fugitive_Emissions": 50,
//         "CO2_Emissions": 187500,
//         "CH4_CO2e": 1250,
//         "Afforestation_Potential": 75,
//         "Trees_Plantable": 75000,
//         "Carbon_Sequestration_Potential": 750,
//         "Deforestation_Impact": 1500,
//         "Methane_Capture_Potential": 75,
//         "Energy_Efficiency_Gains": 2,
//         "Electrification_Impact": 50,
//         "Renewable_Adoption_Potential": 20,
//         "Carbon_Credits_Potential": 1397,
//         "Carbon_Credit_Value": 30,
//         "Estimated_Revenue_from_Credits ": 41910,
//         "Air_Quantity (m3/minute)": 1600.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.4141,
//         "Make_of_Methane (m3/minute)": 8.215,
//         "CO2_conc._in_intake (%)": 0.0325,
//         "CO2_conc._in_return (%)": 0.1593,
//         "Make_of_CO2 (m3/minute)": 2.115,
//         "Coal_Production (TPD)": 120,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 68.5,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.3,
//         "Description": "Raniganj Mine is an underground coal mine located in West Bengal, India, started in 1965. It covers 1,500 hectares and produces 750,000 tons of coal annually. The mine consumes 20 million liters of fuel and 50 MWh of electricity per year. Methane emissions amount to 100 tons, with CO₂ emissions reaching 187,500 tons. The mine has an afforestation potential of 75 hectares, allowing for the planting of 75,000 trees, which could sequester 750 tons of carbon. Methane capture could reduce emissions by 75 tons, with potential energy efficiency gains of 2%. The estimated revenue from carbon credits is $41,910."
//     },
//     {
//         "Mine_ID": 12,
//         "Mine_Name": "Jharia Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Jharkhand",
//         "Latitude": 23.74,
//         "Longitude": 86.41,
//         "Coal_Production": 5000000,
//         "Area_Covered": 6000,
//         "Year_Started": 1970,
//         "Fuel_Consumption": 80000000,
//         "Electricity_Consumption": 250,
//         "Explosives_Used": 45000,
//         "Methane_Emissions": 600,
//         "Fugitive_Emissions": 300,
//         "CO2_Emissions": 1250000,
//         "CH4_CO2e": 7500,
//         "Afforestation_Potential": 400,
//         "Trees_Plantable": 600000,
//         "Carbon_Sequestration_Potential": 4000,
//         "Deforestation_Impact": 10000,
//         "Methane_Capture_Potential": 400,
//         "Energy_Efficiency_Gains": 10,
//         "Electrification_Impact": 250,
//         "Renewable_Adoption_Potential": 60,
//         "Carbon_Credits_Potential": 8120,
//         "Carbon_Credit_Value": 40,
//         "Estimated_Revenue_from_Credits ": 324800,
//         "Air_Quantity (m3/minute)": 3500.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 1.0411,
//         "Make_of_Methane (m3/minute)": 30.454,
//         "CO2_conc._in_intake (%)": 0.0385,
//         "CO2_conc._in_return (%)": 0.2751,
//         "Make_of_CO2 (m3/minute)": 8.314,
//         "Coal_Production (TPD)": 600,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 50.8,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 13.6,
//         "Description": "Jharia Mine (Open-cast) is located in Jharkhand, India, established in 1970. It spans 6,000 hectares and produces 5 million tons of coal annually. The mine consumes 80 million liters of fuel and 250 MWh of electricity each year. Methane emissions total 600 tons, and CO₂ emissions reach 1,250,000 tons. The mine has an afforestation potential of 400 hectares, allowing for the planting of 600,000 trees, sequestering 4,000 tons of carbon. Methane capture could reduce emissions by 400 tons. Estimated revenue from carbon credits is $324,800."
//     },
//     {
//         "Mine_ID": 13,
//         "Mine_Name": "Talcher Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Odisha",
//         "Latitude": 20.95,
//         "Longitude": 85.2,
//         "Coal_Production": 2000000,
//         "Area_Covered": 3000,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 30000000,
//         "Electricity_Consumption": 120,
//         "Explosives_Used": 20000,
//         "Methane_Emissions": 250,
//         "Fugitive_Emissions": 125,
//         "CO2_Emissions": 500000,
//         "CH4_CO2e": 3125,
//         "Afforestation_Potential": 150,
//         "Trees_Plantable": 200000,
//         "Carbon_Sequestration_Potential": 1500,
//         "Deforestation_Impact": 3000,
//         "Methane_Capture_Potential": 150,
//         "Energy_Efficiency_Gains": 5,
//         "Electrification_Impact": 120,
//         "Renewable_Adoption_Potential": 30,
//         "Carbon_Credits_Potential": 4320,
//         "Carbon_Credit_Value": 35,
//         "Estimated_Revenue_from_Credits ": 151200,
//         "Air_Quantity (m3/minute)": 2000.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.6101,
//         "Make_of_Methane (m3/minute)": 12.85,
//         "CO2_conc._in_intake (%)": 0.035,
//         "CO2_conc._in_return (%)": 0.1925,
//         "Make_of_CO2 (m3/minute)": 4.815,
//         "Coal_Production (TPD)": 300,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 42.83,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 10.45,
//         "Description": "Talcher Mine is an open-cast coal mine in Odisha, India, started in 1985. Covering 3,000 hectares, it produces 2 million tons of coal annually. The mine consumes 30 million liters of fuel and 120 MWh of electricity per year, emitting 250 tons of methane and 500,000 tons of CO₂. Afforestation could cover 150 hectares, allowing for 200,000 trees to sequester 1,500 tons of carbon. Methane capture could reduce emissions by 150 tons. Estimated revenue from carbon credits is $151,200."
//     },
//     {
//         "Mine_ID": 14,
//         "Mine_Name": "Korba Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Chhattisgarh",
//         "Latitude": 22.35,
//         "Longitude": 82.68,
//         "Coal_Production": 7000000,
//         "Area_Covered": 9000,
//         "Year_Started": 1975,
//         "Fuel_Consumption": 110000000,
//         "Electricity_Consumption": 380,
//         "Explosives_Used": 55000,
//         "Methane_Emissions": 900,
//         "Fugitive_Emissions": 450,
//         "CO2_Emissions": 1750000,
//         "CH4_CO2e": 11250,
//         "Afforestation_Potential": 600,
//         "Trees_Plantable": 1000000,
//         "Carbon_Sequestration_Potential": 6000,
//         "Deforestation_Impact": 14000,
//         "Methane_Capture_Potential": 700,
//         "Energy_Efficiency_Gains": 12,
//         "Electrification_Impact": 380,
//         "Renewable_Adoption_Potential": 85,
//         "Carbon_Credits_Potential": 13982,
//         "Carbon_Credit_Value": 45,
//         "Estimated_Revenue_from_Credits ": 629190,
//         "Air_Quantity (m3/minute)": 4300.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 1.2311,
//         "Make_of_Methane (m3/minute)": 34.455,
//         "CO2_conc._in_intake (%)": 0.039,
//         "CO2_conc._in_return (%)": 0.2815,
//         "Make_of_CO2 (m3/minute)": 9.725,
//         "Coal_Production (TPD)": 950,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 36.27,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 12.2,
//         "Description": "Korba Mine is an open-cast mine in Chhattisgarh, India, operational since 1975. It spans 9,000 hectares and produces 7 million tons of coal annually. The mine consumes 110 million liters of fuel and 380 MWh of electricity per year. Methane emissions total 900 tons, while CO₂ emissions reach 1,750,000 tons. The mine has an afforestation potential of 600 hectares, with the ability to plant 1 million trees, sequestering 6,000 tons of carbon. Methane capture could reduce emissions by 700 tons, and the estimated revenue from carbon credits is $629,190."
//     },
//     {
//         "Mine_ID": 15,
//         "Mine_Name": "Jharia Mine",
//         "Mine_Type": "Underground",
//         "State": "Jharkhand",
//         "Latitude": 23.75,
//         "Longitude": 86.42,
//         "Coal_Production": 3000000,
//         "Area_Covered": 2000,
//         "Year_Started": 1890,
//         "Fuel_Consumption": 18000000,
//         "Electricity_Consumption": 150,
//         "Explosives_Used": 10000,
//         "Methane_Emissions": 400,
//         "Fugitive_Emissions": 200,
//         "CO2_Emissions": 850000,
//         "CH4_CO2e": 5000,
//         "Afforestation_Potential": 120,
//         "Trees_Plantable": 150000,
//         "Carbon_Sequestration_Potential": 1800,
//         "Deforestation_Impact": 2700,
//         "Methane_Capture_Potential": 200,
//         "Energy_Efficiency_Gains": 4,
//         "Electrification_Impact": 150,
//         "Renewable_Adoption_Potential": 25,
//         "Carbon_Credits_Potential": 7030,
//         "Carbon_Credit_Value": 40,
//         "Estimated_Revenue_from_Credits ": 281200,
//         "Air_Quantity (m3/minute)": 2500.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.7102,
//         "Make_of_Methane (m3/minute)": 18.225,
//         "CO2_conc._in_intake (%)": 0.034,
//         "CO2_conc._in_return (%)": 0.2035,
//         "Make_of_CO2 (m3/minute)": 6.025,
//         "Coal_Production (TPD)": 500,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 36.45,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 9.55,
//         "Description": "Jharia Mine (Underground), located in Jharkhand, India, was established in 1890. Covering 2,000 hectares, it produces 3 million tons of coal annually. The mine consumes 18 million liters of fuel and 150 MWh of electricity. Methane emissions amount to 400 tons, and CO₂ emissions total 850,000 tons. The mine has an afforestation potential of 120 hectares, with 150,000 trees sequestering 1,800 tons of carbon. Methane capture could reduce emissions by 200 tons, and the estimated revenue from carbon credits is $281,200."
//     },
//     {
//         "Mine_ID": 16,
//         "Mine_Name": "Kusmunda Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Chhattisgarh",
//         "Latitude": 22.25,
//         "Longitude": 82.69,
//         "Coal_Production": 10000000,
//         "Area_Covered": 12000,
//         "Year_Started": 1965,
//         "Fuel_Consumption": 150000000,
//         "Electricity_Consumption": 450,
//         "Explosives_Used": 65000,
//         "Methane_Emissions": 1200,
//         "Fugitive_Emissions": 600,
//         "CO2_Emissions": 2400000,
//         "CH4_CO2e": 15000,
//         "Afforestation_Potential": 750,
//         "Trees_Plantable": 1200000,
//         "Carbon_Sequestration_Potential": 8000,
//         "Deforestation_Impact": 17000,
//         "Methane_Capture_Potential": 900,
//         "Energy_Efficiency_Gains": 18,
//         "Electrification_Impact": 450,
//         "Renewable_Adoption_Potential": 90,
//         "Carbon_Credits_Potential": 23958,
//         "Carbon_Credit_Value": 50,
//         "Estimated_Revenue_from_Credits": 1197900,
//         "Air_Quantity (m3/minute)": 4800.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 1.3101,
//         "Make_of_Methane (m3/minute)": 36.295,
//         "CO2_conc._in_intake (%)": 0.036,
//         "CO2_conc._in_return (%)": 0.2955,
//         "Make_of_CO2 (m3/minute)": 11.215,
//         "Coal_Production (TPD)": 1200,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 30.24,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 9.35,
//         "Description": "The Kusmunda Mine, located in Chhattisgarh, India, is an open-cast coal mining operation that commenced in 1965. It spans an area of 12,000 hectares and produces approximately 10,000,000 tons of coal annually. The mine has a significant fuel consumption of 150,000,000 liters and uses 65,000 kg of explosives. Methane emissions from the mine are around 1,200 m³, while CO2 emissions reach 2,400,000 tons. The mine has a notable afforestation potential with 1,200,000 trees plantable and a carbon sequestration potential of 8,000 tons. The Kusmunda Mine also holds a substantial carbon credits potential of 23,958 credits, with an estimated revenue from these credits amounting to ₹1,197,900."
//     },
//     {
//         "Mine_ID": 17,
//         "Mine_Name": "Bhatadi Mine",
//         "Mine_Type": "Underground",
//         "State": "Maharashtra",
//         "Latitude": 20.33,
//         "Longitude": 79.25,
//         "Coal_Production": 800000,
//         "Area_Covered": 1500,
//         "Year_Started": 1945,
//         "Fuel_Consumption": 9000000,
//         "Electricity_Consumption": 90,
//         "Explosives_Used": 25000,
//         "Methane_Emissions": 600,
//         "Fugitive_Emissions": 300,
//         "CO2_Emissions": 120000,
//         "CH4_CO2e": 7500,
//         "Afforestation_Potential": 200,
//         "Trees_Plantable": 250000,
//         "Carbon_Sequestration_Potential": 3200,
//         "Deforestation_Impact": 6000,
//         "Methane_Capture_Potential": 300,
//         "Energy_Efficiency_Gains": 6,
//         "Electrification_Impact": 90,
//         "Renewable_Adoption_Potential": 18,
//         "Carbon_Credits_Potential": 10420,
//         "Carbon_Credit_Value": 35,
//         "Estimated_Revenue_from_Credits": 364700,
//         "Air_Quantity (m3/minute)": 2000.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 0.8503,
//         "Make_of_Methane (m3/minute)": 17.663,
//         "CO2_conc._in_intake (%)": 0.037,
//         "CO2_conc._in_return (%)": 0.2294,
//         "Make_of_CO2 (m3/minute)": 4.354,
//         "Coal_Production (TPD)": 220,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 28.88,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 8.35,
//         "Description": "Situated in Maharashtra, the Bhatadi Mine is an underground operation that started in 1945. Covering an area of 1,500 hectares, it has a coal production capacity of 800,000 tons per year. The mine consumes 9,000,000 liters of fuel and uses 25,000 kg of explosives. Methane emissions are 600 m³, with CO2 emissions totaling 120,000 tons. The Bhatadi Mine's afforestation potential allows for planting 250,000 trees, with a carbon sequestration potential of 3,200 tons. It has a carbon credits potential of 10,420 credits, generating an estimated revenue of ₹364,700 from these credits."
//     },
//     {
//         "Mine_ID": 18,
//         "Mine_Name": "Kendrapara Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Odisha",
//         "Latitude": 20.78,
//         "Longitude": 85.83,
//         "Coal_Production": 5000000,
//         "Area_Covered": 7000,
//         "Year_Started": 1970,
//         "Fuel_Consumption": 70000000,
//         "Electricity_Consumption": 300,
//         "Explosives_Used": 45000,
//         "Methane_Emissions": 1000,
//         "Fugitive_Emissions": 500,
//         "CO2_Emissions": 2000000,
//         "CH4_CO2e": 12500,
//         "Afforestation_Potential": 500,
//         "Trees_Plantable": 800000,
//         "Carbon_Sequestration_Potential": 5000,
//         "Deforestation_Impact": 15000,
//         "Methane_Capture_Potential": 700,
//         "Energy_Efficiency_Gains": 14,
//         "Electrification_Impact": 300,
//         "Renewable_Adoption_Potential": 60,
//         "Carbon_Credits_Potential": 13874,
//         "Carbon_Credit_Value": 45,
//         "Estimated_Revenue_from_Credits": 624330,
//         "Air_Quantity (m3/minute)": 3500.00,
//         "CH4_conc._in_intake (%)": 0,
//         "CH4_conc._in_return (%)": 1.1001,
//         "Make_of_Methane (m3/minute)": 38.503,
//         "CO2_conc._in_intake (%)": 0.035,
//         "CO2_conc._in_return (%)": 0.3125,
//         "Make_of_CO2 (m3/minute)": 10.965,
//         "Coal_Production (TPD)": 500,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 25.84,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 11.17,
//         "Description": "The Kendrapara Mine, located in Odisha, is an open-cast mining operation that began in 1970. The mine covers an area of 7,000 hectares and produces 5,000,000 tons of coal annually. It has a fuel consumption of 70,000,000 liters and uses 45,000 kg of explosives. Methane emissions are 1,000 m³, while CO2 emissions reach 2,000,000 tons. The mine's afforestation potential supports the planting of 800,000 trees, with a carbon sequestration potential of 5,000 tons. The Kendrapara Mine has a carbon credits potential of 13,874 credits, with an estimated revenue of ₹624,330."
//     },
//     {
//         "Mine_ID": 19,
//         "Mine_Name": "Korba Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Chhattisgarh",
//         "Latitude": 22.35,
//         "Longitude": 82.71,
//         "Coal_Production": 10000000,
//         "Area_Covered": 12000,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 120000000,
//         "Electricity_Consumption": 500,
//         "Explosives_Used": 60000,
//         "Methane_Emissions": 2000,
//         "Fugitive_Emissions": 800,
//         "CO2_Emissions": 4000000,
//         "CH4_CO2e": 25000,
//         "Afforestation_Potential": 1000,
//         "Trees_Plantable": 1500000,
//         "Carbon_Sequestration_Potential": 10000,
//         "Deforestation_Impact": 30000,
//         "Methane_Capture_Potential": 1400,
//         "Energy_Efficiency_Gains": 28,
//         "Electrification_Impact": 500,
//         "Renewable_Adoption_Potential": 100,
//         "Carbon_Credits_Potential": 26500,
//         "Carbon_Credit_Value": 50,
//         "Estimated_Revenue_from_Credits ": 1325000,
//         "Air_Quantity (m3/minute)": 5000.00,
//         "CH4_conc._in_intake (%)": 0.01,
//         "CH4_conc._in_return (%)": 1.2000,
//         "Make_of_Methane (m3/minute)": 60.000,
//         "CO2_conc._in_intake (%)": 0.050,
//         "CO2_conc._in_return (%)": 0.4000,
//         "Make_of_CO2 (m3/minute)": 20.000,
//         "Coal_Production (TPD)": 800,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 32.00,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.00,
//         "Description": "Korba Mine is a large open-cast mine located in Chhattisgarh, India. The mine has been in operation since 1985 and is known for its significant coal production capacity of 10 million tonnes per year. Covering an area of 12,000 hectares, Korba Mine is a major source of energy, consuming 120 million liters of fuel annually. The mine is a key player in India's energy sector, contributing both to coal extraction and emissions management through its methane capture potential and renewable adoption initiatives."
//     },
//     {
//         "Mine_ID": 20,
//         "Mine_Name": "Singrauli Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Madhya Pradesh",
//         "Latitude": 24.18,
//         "Longitude": 82.65,
//         "Coal_Production": 9000000,
//         "Area_Covered": 10000,
//         "Year_Started": 1975,
//         "Fuel_Consumption": 100000000,
//         "Electricity_Consumption": 450,
//         "Explosives_Used": 55000,
//         "Methane_Emissions": 1800,
//         "Fugitive_Emissions": 700,
//         "CO2_Emissions": 3600000,
//         "CH4_CO2e": 22500,
//         "Afforestation_Potential": 800,
//         "Trees_Plantable": 1200000,
//         "Carbon_Sequestration_Potential": 9000,
//         "Deforestation_Impact": 27000,
//         "Methane_Capture_Potential": 1260,
//         "Energy_Efficiency_Gains": 25,
//         "Electrification_Impact": 450,
//         "Renewable_Adoption_Potential": 90,
//         "Carbon_Credits_Potential": 23355,
//         "Carbon_Credit_Value": 40,
//         "Estimated_Revenue_from_Credits ": 934200,
//         "Air_Quantity (m3/minute)": 4500.00,
//         "CH4_conc._in_intake (%)": 0.015,
//         "CH4_conc._in_return (%)": 1.1500,
//         "Make_of_Methane (m3/minute)": 51.750,
//         "CO2_conc._in_intake (%)": 0.045,
//         "CO2_conc._in_return (%)": 0.3750,
//         "Make_of_CO2 (m3/minute)": 17.063,
//         "Coal_Production (TPD)": 700,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 29.78,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 12.58,
//         "Description": "Located in Madhya Pradesh, Singrauli Mine is an open-cast coal mine that began operations in 1975. The mine covers 10,000 hectares and produces 9 million tonnes of coal annually. Singrauli is focused on sustainability, with a methane capture potential of 1,260 m3 per minute and a strong afforestation program. The mine is also working towards increasing energy efficiency by 25% and adopting renewable energy solutions. Singrauli plays a vital role in meeting India's coal demand while exploring pathways to reduce its carbon footprint."
//     },
//     {
//         "Mine_ID": 21,
//         "Mine_Name": "Dhanbad Mine",
//         "Mine_Type": "Underground",
//         "State": "Jharkhand",
//         "Latitude": 23.79,
//         "Longitude": 86.44,
//         "Coal_Production": 8000000,
//         "Area_Covered": 15000,
//         "Year_Started": 1950,
//         "Fuel_Consumption": 80000000,
//         "Electricity_Consumption": 400,
//         "Explosives_Used": 50000,
//         "Methane_Emissions": 2500,
//         "Fugitive_Emissions": 1000,
//         "CO2_Emissions": 3500000,
//         "CH4_CO2e": 30000,
//         "Afforestation_Potential": 1200,
//         "Trees_Plantable": 1800000,
//         "Carbon_Sequestration_Potential": 12000,
//         "Deforestation_Impact": 36000,
//         "Methane_Capture_Potential": 1800,
//         "Energy_Efficiency_Gains": 36,
//         "Electrification_Impact": 400,
//         "Renewable_Adoption_Potential": 80,
//         "Carbon_Credits_Potential": 27416,
//         "Carbon_Credit_Value": 45,
//         "Estimated_Revenue_from_Credits ": 1233720,
//         "Air_Quantity (m3/minute)": 5500.00,
//         "CH4_conc._in_intake (%)": 0.020,
//         "CH4_conc._in_return (%)": 1.2500,
//         "Make_of_Methane (m3/minute)": 68.750,
//         "CO2_conc._in_intake (%)": 0.060,
//         "CO2_conc._in_return (%)": 0.4200,
//         "Make_of_CO2 (m3/minute)": 23.100,
//         "Coal_Production (TPD)": 600,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 31.25,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 14.58,
//         "Description": "Dhanbad Mine is one of the oldest underground coal mines in India, operating since 1950. Located in Jharkhand, it covers an area of 15,000 hectares and produces 8 million tonnes of coal annually. The mine is notable for its high methane emissions and has a significant methane capture potential of 1,800 m3 per minute. Dhanbad Mine is also part of a large-scale afforestation program to mitigate its environmental impact, with the potential to plant 1.8 million trees."
//     },
//     {
//         "Mine_ID": 22,
//         "Mine_Name": "Bokaro Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Jharkhand",
//         "Latitude": 23.78,
//         "Longitude": 85.98,
//         "Coal_Production": 8500000,
//         "Area_Covered": 14000,
//         "Year_Started": 1970,
//         "Fuel_Consumption": 85000000,
//         "Electricity_Consumption": 420,
//         "Explosives_Used": 55000,
//         "Methane_Emissions": 2300,
//         "Fugitive_Emissions": 900,
//         "CO2_Emissions": 3700000,
//         "CH4_CO2e": 27000,
//         "Afforestation_Potential": 1000,
//         "Trees_Plantable": 1600000,
//         "Carbon_Sequestration_Potential": 11000,
//         "Deforestation_Impact": 33000,
//         "Methane_Capture_Potential": 1530,
//         "Energy_Efficiency_Gains": 30,
//         "Electrification_Impact": 420,
//         "Renewable_Adoption_Potential": 90,
//         "Carbon_Credits_Potential": 27000,
//         "Carbon_Credit_Value": 55,
//         "Estimated_Revenue_from_Credits ": 1485000,
//         "Air_Quantity (m3/minute)": 5000.00,
//         "CH4_conc._in_intake (%)": 0.018,
//         "CH4_conc._in_return (%)": 1.2000,
//         "Make_of_Methane (m3/minute)": 60.000,
//         "CO2_conc._in_intake (%)": 0.050,
//         "CO2_conc._in_return (%)": 0.4000,
//         "Make_of_CO2 (m3/minute)": 20.000,
//         "Coal_Production (TPD)": 700,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 32.86,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 14.50,
//         "Description": "Bokaro Mine, an open-cast mine located in Jharkhand, covers 14,000 hectares and has been in operation since 1970. It produces 8.5 million tonnes of coal annually and consumes 85 million liters of fuel. Bokaro Mine has a methane capture potential of 1,530 m3 per minute and a carbon credit potential worth 1.48 million USD. The mine is actively involved in environmental initiatives, including afforestation and energy efficiency improvements."
//     },
//     {
//         "Mine_ID": 23,
//         "Mine_Name": "Ranchi Mine",
//         "Mine_Type": "Underground",
//         "State": "Jharkhand",
//         "Latitude": 23.37,
//         "Longitude": 85.32,
//         "Coal_Production": 9000000,
//         "Area_Covered": 16000,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 90000000,
//         "Electricity_Consumption": 450,
//         "Explosives_Used": 60000,
//         "Methane_Emissions": 2800,
//         "Fugitive_Emissions": 1100,
//         "CO2_Emissions": 4000000,
//         "CH4_CO2e": 32000,
//         "Afforestation_Potential": 1300,
//         "Trees_Plantable": 2000000,
//         "Carbon_Sequestration_Potential": 13000,
//         "Deforestation_Impact": 39000,
//         "Methane_Capture_Potential": 2100,
//         "Energy_Efficiency_Gains": 39,
//         "Electrification_Impact": 450,
//         "Renewable_Adoption_Potential": 100,
//         "Carbon_Credits_Potential": 31900,
//         "Carbon_Credit_Value": 50,
//         "Estimated_Revenue_from_Credits ": 1595000,
//         "Air_Quantity (m3/minute)": 6000.00,
//         "CH4_conc._in_intake (%)": 0.022,
//         "CH4_conc._in_return (%)": 1.3000,
//         "Make_of_Methane (m3/minute)": 78.000,
//         "CO2_conc._in_intake (%)": 0.070,
//         "CO2_conc._in_return (%)": 0.4500,
//         "Make_of_CO2 (m3/minute)": 31.500,
//         "Coal_Production (TPD)": 800,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 35.00,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.00,
//         "Description": "Ranchi Mine, an underground coal mine in Jharkhand, started operations in 1985 and covers 16,000 hectares. The mine produces 9 million tonnes of coal per year and has a significant focus on methane capture and energy efficiency. With a methane capture potential of 2,100 m3 per minute and an afforestation program capable of planting 2 million trees, Ranchi Mine is working to reduce its carbon emissions and increase its use of renewable energy."
//     },
//     {
//         "Mine_ID": 24,
//         "Mine_Name": "Jharia Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Jharkhand",
//         "Latitude": 23.75,
//         "Longitude": 86.15,
//         "Coal_Production": 9500000,
//         "Area_Covered": 17000,
//         "Year_Started": 1990,
//         "Fuel_Consumption": 95000000,
//         "Electricity_Consumption": 470,
//         "Explosives_Used": 65000,
//         "Methane_Emissions": 2900,
//         "Fugitive_Emissions": 1200,
//         "CO2_Emissions": 4200000,
//         "CH4_CO2e": 33000,
//         "Afforestation_Potential": 1400,
//         "Trees_Plantable": 2200000,
//         "Carbon_Sequestration_Potential": 14000,
//         "Deforestation_Impact": 42000,
//         "Methane_Capture_Potential": 2250,
//         "Energy_Efficiency_Gains": 42,
//         "Electrification_Impact": 470,
//         "Renewable_Adoption_Potential": 110,
//         "Carbon_Credits_Potential": 33000,
//         "Carbon_Credit_Value": 52,
//         "Estimated_Revenue_from_Credits": 1716000,
//         "Air_Quantity (m3/minute)": 6500.00,
//         "CH4_conc._in_intake (%)": 0.023,
//         "CH4_conc._in_return (%)": 1.3500,
//         "Make_of_Methane (m3/minute)": 85.500,
//         "CO2_conc._in_intake (%)": 0.080,
//         "CO2_conc._in_return (%)": 0.4600,
//         "Make_of_CO2 (m3/minute)": 36.800,
//         "Coal_Production (TPD)": 850,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 36.42,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.40,
//         "Description": "Jharia Mine is one of the largest open-cast coal mines located in Jharkhand, India. It has been operational since 1990 and covers a vast area of 17,000 hectares. Known for its high coal production rate of 9.5 million tons per year, the mine is also a significant source of methane emissions. Its operations heavily rely on fuel and electricity, while it offers notable potential for afforestation and methane capture."
//     },
//     {
//         "Mine_ID": 25,
//         "Mine_Name": "Korba Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Chhattisgarh",
//         "Latitude": 22.35,
//         "Longitude": 82.68,
//         "Coal_Production": 8500000,
//         "Area_Covered": 15000,
//         "Year_Started": 1995,
//         "Fuel_Consumption": 85000000,
//         "Electricity_Consumption": 420,
//         "Explosives_Used": 60000,
//         "Methane_Emissions": 2700,
//         "Fugitive_Emissions": 1150,
//         "CO2_Emissions": 3900000,
//         "CH4_CO2e": 31000,
//         "Afforestation_Potential": 1200,
//         "Trees_Plantable": 1800000,
//         "Carbon_Sequestration_Potential": 12000,
//         "Deforestation_Impact": 36000,
//         "Methane_Capture_Potential": 2000,
//         "Energy_Efficiency_Gains": 36,
//         "Electrification_Impact": 420,
//         "Renewable_Adoption_Potential": 90,
//         "Carbon_Credits_Potential": 31000,
//         "Carbon_Credit_Value": 48,
//         "Estimated_Revenue_from_Credits": 1488000,
//         "Air_Quantity (m3/minute)": 5800.00,
//         "CH4_conc._in_intake (%)": 0.021,
//         "CH4_conc._in_return (%)": 1.2800,
//         "Make_of_Methane (m3/minute)": 74.400,
//         "CO2_conc._in_intake (%)": 0.060,
//         "CO2_conc._in_return (%)": 0.4300,
//         "Make_of_CO2 (m3/minute)": 29.400,
//         "Coal_Production (TPD)": 780,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 34.44,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 14.75,
//         "Description": "Korba Mine, located in Chhattisgarh, India, is an open-cast mine known for producing 8.5 million tons of coal annually. This mine spans 15,000 hectares and has been active since 1995. With a significant focus on coal extraction, the Korba Mine also generates notable methane and CO2 emissions. The mine presents considerable potential for renewable energy adoption and carbon credit generation."
//     },
//     {
//         "Mine_ID": 26,
//         "Mine_Name": "Bilaspur Mine",
//         "Mine_Type": "Underground",
//         "State": "Chhattisgarh",
//         "Latitude": 22.09,
//         "Longitude": 82.14,
//         "Coal_Production": 8700000,
//         "Area_Covered": 15500,
//         "Year_Started": 2000,
//         "Fuel_Consumption": 87000000,
//         "Electricity_Consumption": 430,
//         "Explosives_Used": 61000,
//         "Methane_Emissions": 2750,
//         "Fugitive_Emissions": 1180,
//         "CO2_Emissions": 3950000,
//         "CH4_CO2e": 31500,
//         "Afforestation_Potential": 1250,
//         "Trees_Plantable": 1900000,
//         "Carbon_Sequestration_Potential": 12500,
//         "Deforestation_Impact": 37500,
//         "Methane_Capture_Potential": 2050,
//         "Energy_Efficiency_Gains": 37,
//         "Electrification_Impact": 430,
//         "Renewable_Adoption_Potential": 95,
//         "Carbon_Credits_Potential": 31500,
//         "Carbon_Credit_Value": 49,
//         "Estimated_Revenue_from_Credits": 1543500,
//         "Air_Quantity (m3/minute)": 5900.00,
//         "CH4_conc._in_intake (%)": 0.022,
//         "CH4_conc._in_return (%)": 1.2900,
//         "Make_of_Methane (m3/minute)": 76.600,
//         "CO2_conc._in_intake (%)": 0.065,
//         "CO2_conc._in_return (%)": 0.4400,
//         "Make_of_CO2 (m3/minute)": 30.000,
//         "Coal_Production (TPD)": 800,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 35.31,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.00,
//         "Description": "Bilaspur Mine is an underground mine located in Chhattisgarh, India, operational since 2000. It produces 8.7 million tons of coal annually and covers an area of 15,500 hectares. This mine has substantial fuel and electricity requirements, but it offers significant methane capture and carbon sequestration opportunities."
//     },
//     {
//         "Mine_ID": 27,
//         "Mine_Name": "Sundergarh Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Odisha",
//         "Latitude": 21.53,
//         "Longitude": 85.87,
//         "Coal_Production": 9000000,
//         "Area_Covered": 16000,
//         "Year_Started": 1990,
//         "Fuel_Consumption": 90000000,
//         "Electricity_Consumption": 440,
//         "Explosives_Used": 62000,
//         "Methane_Emissions": 2800,
//         "Fugitive_Emissions": 1200,
//         "CO2_Emissions": 4000000,
//         "CH4_CO2e": 32000,
//         "Afforestation_Potential": 1300,
//         "Trees_Plantable": 2000000,
//         "Carbon_Sequestration_Potential": 13000,
//         "Deforestation_Impact": 39000,
//         "Methane_Capture_Potential": 2100,
//         "Energy_Efficiency_Gains": 38,
//         "Electrification_Impact": 440,
//         "Renewable_Adoption_Potential": 100,
//         "Carbon_Credits_Potential": 32000,
//         "Carbon_Credit_Value": 50,
//         "Estimated_Revenue_from_Credits": 1600000,
//         "Air_Quantity (m3/minute)": 6000.00,
//         "CH4_conc._in_intake (%)": 0.023,
//         "CH4_conc._in_return (%)": 1.3000,
//         "Make_of_Methane (m3/minute)": 78.000,
//         "CO2_conc._in_intake (%)": 0.070,
//         "CO2_conc._in_return (%)": 0.4500,
//         "Make_of_CO2 (m3/minute)": 30.600,
//         "Coal_Production (TPD)": 825,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 36.12,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.45,
//         "Description": "Sundergarh Mine, located in Odisha, India, is an open-cast coal mine that has been in operation since 1990. It produces 9 million tons of coal annually and covers an area of 16,000 hectares. The mine is a major contributor to methane and CO2 emissions but offers significant potential for afforestation, carbon sequestration, and methane capture."
//     },
//     {
//         "Mine_ID": 28,
//         "Mine_Name": "Barbil Mine",
//         "Mine_Type": "Underground",
//         "State": "Odisha",
//         "Latitude": 21.63,
//         "Longitude": 85.30,
//         "Coal_Production": 9500000,
//         "Area_Covered": 16500,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 95000000,
//         "Electricity_Consumption": 450,
//         "Explosives_Used": 63000,
//         "Methane_Emissions": 2850,
//         "Fugitive_Emissions": 1220,
//         "CO2_Emissions": 4050000,
//         "CH4_CO2e": 32500,
//         "Afforestation_Potential": 1350,
//         "Trees_Plantable": 2100000,
//         "Carbon_Sequestration_Potential": 13500,
//         "Deforestation_Impact": 40500,
//         "Methane_Capture_Potential": 2150,
//         "Energy_Efficiency_Gains": 39,
//         "Electrification_Impact": 450,
//         "Renewable_Adoption_Potential": 105,
//         "Carbon_Credits_Potential": 32500,
//         "Carbon_Credit_Value": 52,
//         "Estimated_Revenue_from_Credits": 1695000,
//         "Air_Quantity (m3/minute)": 6100.00,
//         "CH4_conc._in_intake (%)": 0.025,
//         "CH4_conc._in_return (%)": 1.3200,
//         "Make_of_Methane (m3/minute)": 80.000,
//         "CO2_conc._in_intake (%)": 0.075,
//         "CO2_conc._in_return (%)": 0.4600,
//         "Make_of_CO2 (m3/minute)": 31.000,
//         "Coal_Production (TPD)": 850,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 37.00,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.75,
//         "Description": "Barbil Mine, situated in Odisha, India, is an underground coal mine that has been operational since 1985. With an annual coal production of 9.5 million tons and an area coverage of 16,500 hectares, the mine is a significant source of methane and CO2 emissions. It has a high potential for carbon sequestration and renewable energy adoption."
//     },
//     {
//         "Mine_ID": 29,
//         "Mine_Name": "Chandrapur Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Maharashtra",
//         "Latitude": 20.02,
//         "Longitude": 79.30,
//         "Coal_Production": 10000000,
//         "Area_Covered": 17000,
//         "Year_Started": 1995,
//         "Fuel_Consumption": 100000000,
//         "Electricity_Consumption": 460,
//         "Explosives_Used": 65000,
//         "Methane_Emissions": 2900,
//         "Fugitive_Emissions": 1250,
//         "CO2_Emissions": 4100000,
//         "CH4_CO2e": 33000,
//         "Afforestation_Potential": 1400,
//         "Trees_Plantable": 2200000,
//         "Carbon_Sequestration_Potential": 14000,
//         "Deforestation_Impact": 42000,
//         "Methane_Capture_Potential": 2200,
//         "Energy_Efficiency_Gains": 40,
//         "Electrification_Impact": 460,
//         "Renewable_Adoption_Potential": 110,
//         "Carbon_Credits_Potential": 33000,
//         "Carbon_Credit_Value": 54,
//         "Estimated_Revenue_from_Credits": 1782000,
//         "Air_Quantity (m3/minute)": 6200.00,
//         "CH4_conc._in_intake (%)": 0.027,
//         "CH4_conc._in_return (%)": 1.3400,
//         "Make_of_Methane (m3/minute)": 82.000,
//         "CO2_conc._in_intake (%)": 0.080,
//         "CO2_conc._in_return (%)": 0.4700,
//         "Make_of_CO2 (m3/minute)": 32.500,
//         "Coal_Production (TPD)": 915,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 37.88,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.00,
//         "Description": "Chandrapur Mine, located in Maharashtra, India, is an open-cast coal mine that has been operational since 1995. It produces 10 million tons of coal annually and spans an area of 17,000 hectares. The mine is a major source of greenhouse gas emissions but has considerable potential for carbon credits, afforestation, and energy efficiency improvements."
//     },
//     {
//         "Mine_ID": 30,
//         "Mine_Name": "Raigarh Mine",
//         "Mine_Type": "Underground",
//         "State": "Chhattisgarh",
//         "Latitude": 21.90,
//         "Longitude": 83.35,
//         "Coal_Production": 8500000,
//         "Area_Covered": 15500,
//         "Year_Started": 1987,
//         "Fuel_Consumption": 85000000,
//         "Electricity_Consumption": 440,
//         "Explosives_Used": 62000,
//         "Methane_Emissions": 2750,
//         "Fugitive_Emissions": 1200,
//         "CO2_Emissions": 3950000,
//         "CH4_CO2e": 32000,
//         "Afforestation_Potential": 1300,
//         "Trees_Plantable": 2000000,
//         "Carbon_Sequestration_Potential": 13000,
//         "Deforestation_Impact": 39000,
//         "Methane_Capture_Potential": 2100,
//         "Energy_Efficiency_Gains": 38,
//         "Electrification_Impact": 440,
//         "Renewable_Adoption_Potential": 100,
//         "Carbon_Credits_Potential": 32000,
//         "Carbon_Credit_Value": 51,
//         "Estimated_Revenue_from_Credits": 1632000,
//         "Air_Quantity (m3/minute)": 6000.00,
//         "CH4_conc._in_intake (%)": 0.022,
//         "CH4_conc._in_return (%)": 1.2900,
//         "Make_of_Methane (m3/minute)": 77.000,
//         "CO2_conc._in_intake (%)": 0.068,
//         "CO2_conc._in_return (%)": 0.4400,
//         "Make_of_CO2 (m3/minute)": 29.700,
//         "Coal_Production (TPD)": 740,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 32.35,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.17,
//         "Description": "Raigarh Mine, located in Chhattisgarh, India, is an underground coal mine that has been operational since 1987. It produces 8.5 million tons of coal annually and covers an area of 15,500 hectares. The mine is significant for its methane and CO2 emissions but also has strong potential for carbon credits, afforestation, and energy efficiency improvements."
//     },
//     {
//         "Mine_ID": 31,
//         "Mine_Name": "Singareni Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Telangana",
//         "Latitude": 17.58,
//         "Longitude": 80.23,
//         "Coal_Production": 12000000,
//         "Area_Covered": 18500,
//         "Year_Started": 1990,
//         "Fuel_Consumption": 120000000,
//         "Electricity_Consumption": 500,
//         "Explosives_Used": 70000,
//         "Methane_Emissions": 3100,
//         "Fugitive_Emissions": 1400,
//         "CO2_Emissions": 4500000,
//         "CH4_CO2e": 35000,
//         "Afforestation_Potential": 1600,
//         "Trees_Plantable": 2500000,
//         "Carbon_Sequestration_Potential": 16000,
//         "Deforestation_Impact": 45000,
//         "Methane_Capture_Potential": 2400,
//         "Energy_Efficiency_Gains": 45,
//         "Electrification_Impact": 500,
//         "Renewable_Adoption_Potential": 120,
//         "Carbon_Credits_Potential": 35000,
//         "Carbon_Credit_Value": 56,
//         "Estimated_Revenue_from_Credits ": 1960000,
//         "Air_Quantity (m3/minute)": 6400.00,
//         "CH4_conc._in_intake (%)": 0.030,
//         "CH4_conc._in_return (%)": 1.4000,
//         "Make_of_Methane (m3/minute)": 87.000,
//         "CO2_conc._in_intake (%)": 0.085,
//         "CO2_conc._in_return (%)": 0.5000,
//         "Make_of_CO2 (m3/minute)": 34.800,
//         "Coal_Production (TPD)": 915,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 34.08,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.63
//     },
//     {
//         "Mine_ID": 32,
//         "Mine_Name": "CIL Mine",
//         "Mine_Type": "Underground",
//         "State": "Jharkhand",
//         "Latitude": 23.56,
//         "Longitude": 85.42,
//         "Coal_Production": 9500000,
//         "Area_Covered": 16000,
//         "Year_Started": 1985,
//         "Fuel_Consumption": 95000000,
//         "Electricity_Consumption": 470,
//         "Explosives_Used": 67000,
//         "Methane_Emissions": 2900,
//         "Fugitive_Emissions": 1300,
//         "CO2_Emissions": 4100000,
//         "CH4_CO2e": 33000,
//         "Afforestation_Potential": 1450,
//         "Trees_Plantable": 2100000,
//         "Carbon_Sequestration_Potential": 14500,
//         "Deforestation_Impact": 41000,
//         "Methane_Capture_Potential": 2300,
//         "Energy_Efficiency_Gains": 43,
//         "Electrification_Impact": 470,
//         "Renewable_Adoption_Potential": 105,
//         "Carbon_Credits_Potential": 33000,
//         "Carbon_Credit_Value": 53,
//         "Estimated_Revenue_from_Credits ": 1749000,
//         "Air_Quantity (m3/minute)": 6100.00,
//         "CH4_conc._in_intake (%)": 0.025,
//         "CH4_conc._in_return (%)": 1.3400,
//         "Make_of_Methane (m3/minute)": 80.000,
//         "CO2_conc._in_intake (%)": 0.075,
//         "CO2_conc._in_return (%)": 0.4600,
//         "Make_of_CO2 (m3/minute)": 31.400,
//         "Coal_Production (TPD)": 855,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 34.83,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.05
//     },
//     {
//         "Mine_ID": 33,
//         "Mine_Name": "Barmer Coal Mine",
//         "Mine_Type": "Open-cast",
//         "State": "Rajasthan",
//         "Latitude": 25.69,
//         "Longitude": 71.14,
//         "Coal_Production": 8000000,
//         "Area_Covered": 15000,
//         "Year_Started": 2000,
//         "Fuel_Consumption": 80000000,
//         "Electricity_Consumption": 400,
//         "Explosives_Used": 60000,
//         "Methane_Emissions": 2500,
//         "Fugitive_Emissions": 1200,
//         "CO2_Emissions": 3700000,
//         "CH4_CO2e": 31000,
//         "Afforestation_Potential": 1350,
//         "Trees_Plantable": 2000000,
//         "Carbon_Sequestration_Potential": 13500,
//         "Deforestation_Impact": 37000,
//         "Methane_Capture_Potential": 2100,
//         "Energy_Efficiency_Gains": 40,
//         "Electrification_Impact": 400,
//         "Renewable_Adoption_Potential": 90,
//         "Carbon_Credits_Potential": 31000,
//         "Carbon_Credit_Value": 55,
//         "Estimated_Revenue_from_Credits ": 1705000,
//         "Air_Quantity (m3/minute)": 6000.00,
//         "CH4_conc._in_intake (%)": 0.020,
//         "CH4_conc._in_return (%)": 1.2000,
//         "Make_of_Methane (m3/minute)": 72.000,
//         "CO2_conc._in_intake (%)": 0.080,
//         "CO2_conc._in_return (%)": 0.4200,
//         "Make_of_CO2 (m3/minute)": 29.800,
//         "Coal_Production (TPD)": 730,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 31.25,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 15.55
//     },
//     {
//         "Mine_ID": 34,
//         "Mine_Name": "Kolkata Coal Mine",
//         "Mine_Type": "Underground",
//         "State": "West Bengal",
//         "Latitude": 22.57,
//         "Longitude": 88.36,
//         "Coal_Production": 11000000,
//         "Area_Covered": 18000,
//         "Year_Started": 1980,
//         "Fuel_Consumption": 110000000,
//         "Electricity_Consumption": 550,
//         "Explosives_Used": 80000,
//         "Methane_Emissions": 3300,
//         "Fugitive_Emissions": 1400,
//         "CO2_Emissions": 4700000,
//         "CH4_CO2e": 36000,
//         "Afforestation_Potential": 1700,
//         "Trees_Plantable": 2600000,
//         "Carbon_Sequestration_Potential": 17000,
//         "Deforestation_Impact": 47000,
//         "Methane_Capture_Potential": 2500,
//         "Energy_Efficiency_Gains": 50,
//         "Electrification_Impact": 550,
//         "Renewable_Adoption_Potential": 125,
//         "Carbon_Credits_Potential": 36000,
//         "Carbon_Credit_Value": 58,
//         "Estimated_Revenue_from_Credits ": 2088000,
//         "Air_Quantity (m3/minute)": 6700.00,
//         "CH4_conc._in_intake (%)": 0.028,
//         "CH4_conc._in_return (%)": 1.5000,
//         "Make_of_Methane (m3/minute)": 90.000,
//         "CO2_conc._in_intake (%)": 0.090,
//         "CO2_conc._in_return (%)": 0.4700,
//         "Make_of_CO2 (m3/minute)": 35.200,
//         "Coal_Production (TPD)": 950,
//         "Rate_of_Methane_Emission_during_Mining (m3/tonne)": 30.00,
//         "Rate_of_CO2_Emission_during_Mining (m3/tonne)": 16.56
//     }
// ]

const getMines = async () => {
    const res = await fetch("http://localhost:3000/api/mines")
    const data = res.json();
    return data;

}
const Page = async () => {
    const min = await getMines();
    const mines = min.mine
    // console.log(mines[0]);

    return (
        <>
            {/* {JSON.stringify(mines)} */}
            <div className="flex p-4 gap-4 justify-center">
                <Input type="text" className="mx-10 p-4" placeholder="Search..." />
                <Button className="p-4">Search</Button>
                <Button className="p-4">Filter</Button>
            </div>
            <div className="grid grid-cols-3 gap-5 p-4 m-4">
                {mines.map((el) => {
                    return <div key={el._id}><MiniCard2 mines={el} /></div>
                })}

            </div>
            {/* <MineCard mines={mines[0]} /> */}
        </>
    )
}

export default Page